travis:
  secure:
    BINSTAR_TOKEN: kQ1wJzfxL43GcZ4DMqn8At6BxWN49MFeFhiBSdEpofmRoiYwZxEMbdMBv1UbEfEHOmQuwO5i+jiWcV3eiIL5EKY0MsX4ACf71YMN07FobzM1agG60CBg1wF9bz4eSR+aNAjSgKhcfowLRSdPFj4xdE17XnAMLOO/1guDmZMlM5idQ+SUYPR99LgGcCo2iyud32GvtPXfRYGyWHVt8Bdr8iy9J6pxtu5zwKRHFQ7ToXAaL4yo8T0xMThCVcwuE4LbHR3MvoPqqKIJ5OoeMkr6Vzx74oSSX5NzKrnEXmmwadghsbwPQpbq2hZCEwywDqk0+DgH2PIdoRXz9ZEGCY5w5VHK3q8aLkf4U0iP9aWj0pns8Tyoj2MCK4r2dWIiXRQ3CV+BN/jsDs1cpatnpUGniPpuyvOwVvXqZsCshCa+rvpJhj+uihkiNEbrE7dsMAZAAXqFUo1KpN1L+W5KOuEJ1jJ+CWo1huUhYRximUx4duHdlczRzD9qfdgJjNdqJTEOyuU7CHKo4uLPa1KbZz4Fekk6ZsQZ0vrBZdAxDEyxDAxkXPd9qhohT8qYR/JC2miRpTcaHDJWBSHLJPWmsatmhfI9jfeuLpxmU7NWg2ijn+iajhe9lAZGUqxfa2T0idz7QxdONzxtDYryEf7StHoqeIwEM1driOgUUNLOvlfgP/U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
